# Generated by Django 5.2 on 2025-04-14 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(related_name='get_student', to='user_app.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_line',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(related_name='get_student', to='user_app.groupstudent'),
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('ful_name', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('descriptions', models.CharField(blank=True, max_length=500, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_app.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
