# Generated by Django 5.2 on 2025-04-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_student_course_student_is_line_alter_student_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_line',
        ),
        migrations.DeleteModel(
            name='Parents',
        ),
    ]
